In [1]:
import importlib

In [ ]:
from datasets import mini, olist

importlib.reload(mini)
pass

In [3]:
olist.sales_data

shape: (108_323, 15)
┌──────────────┬──────────────┬──────────────┬──────────────┬───┬───────┬─────────┬──────┬─────────┐
│ product_id   ┆ product_cate ┆ seller_id    ┆ seller_state ┆ … ┆ month ┆ quarter ┆ week ┆ revenue │
│ ---          ┆ gory_name_en ┆ ---          ┆ ---          ┆   ┆ ---   ┆ ---     ┆ ---  ┆ ---     │
│ str          ┆ glish        ┆ str          ┆ str          ┆   ┆ i8    ┆ i8      ┆ i8   ┆ f64     │
│              ┆ ---          ┆              ┆              ┆   ┆       ┆         ┆      ┆         │
│              ┆ str          ┆              ┆              ┆   ┆       ┆         ┆      ┆         │
╞══════════════╪══════════════╪══════════════╪══════════════╪═══╪═══════╪═════════╪══════╪═════════╡
│ 4244733e06e7 ┆ cool_stuff   ┆ 48436dade18a ┆ SP           ┆ … ┆ 9     ┆ 3       ┆ 37   ┆ 72.19   │
│ ecb4970a6e26 ┆              ┆ c8b2bce089ec ┆              ┆   ┆       ┆         ┆      ┆         │
│ 83c13e…      ┆              ┆ 2a0412…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ e5f2d52b8021 ┆ pet_shop     ┆ dd7ddc04e1b6 ┆ SP           ┆ … ┆ 4     ┆ 2       ┆ 17   ┆ 259.83  │
│ 89ee658865ca ┆              ┆ c2c614352b38 ┆              ┆   ┆       ┆         ┆      ┆         │
│ 93d83a…      ┆              ┆ 3efe2d…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ c777355d18b7 ┆ furniture_de ┆ 5b51032eddd2 ┆ MG           ┆ … ┆ 1     ┆ 1       ┆ 2    ┆ 216.87  │
│ 2b67abbeef9d ┆ cor          ┆ 42adc84c38ac ┆              ┆   ┆       ┆         ┆      ┆         │
│ f44fd0…      ┆              ┆ ab88f2…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ 7634da152a46 ┆ perfumery    ┆ 9d7a1d34a505 ┆ SP           ┆ … ┆ 8     ┆ 3       ┆ 32   ┆ 25.78   │
│ 10f1595efa32 ┆              ┆ 240900642527 ┆              ┆   ┆       ┆         ┆      ┆         │
│ f14722…      ┆              ┆ 5ba1c2…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ ac6c3623068f ┆ garden_tools ┆ df560393f3a5 ┆ PR           ┆ … ┆ 2     ┆ 1       ┆ 5    ┆ 218.04  │
│ 30de03045865 ┆              ┆ 1e74553ab940 ┆              ┆   ┆       ┆         ┆      ┆         │
│ e4e100…      ┆              ┆ 04ba5c…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ …            ┆ …            ┆ …            ┆ …            ┆ … ┆ …     ┆ …       ┆ …    ┆ …       │
│ 4aa6014eceb6 ┆ housewares   ┆ b8bc237ba378 ┆ SC           ┆ … ┆ 4     ┆ 2       ┆ 17   ┆ 343.4   │
│ 82077f9dc4bf ┆              ┆ 8b23da09c0f1 ┆              ┆   ┆       ┆         ┆      ┆         │
│ febc05…      ┆              ┆ f3a328…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ 32e07fd91582 ┆ computers_ac ┆ f3c38ab65283 ┆ SP           ┆ … ┆ 7     ┆ 3       ┆ 28   ┆ 386.53  │
│ 2b0765e448c4 ┆ cessories    ┆ 6d21de61fb83 ┆              ┆   ┆       ┆         ┆      ┆         │
│ dd74c8…      ┆              ┆ 14b691…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ 72a30483855e ┆ sports_leisu ┆ c3cfdc648177 ┆ PR           ┆ … ┆ 10    ┆ 4       ┆ 43   ┆ 116.85  │
│ 2eafc67aee5d ┆ re           ┆ fdbbbb35635a ┆              ┆   ┆       ┆         ┆      ┆         │
│ c25604…      ┆              ┆ 37472c…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ 9c422a519119 ┆ computers_ac ┆ 2b3e4a2a3ea8 ┆ SP           ┆ … ┆ 8     ┆ 3       ┆ 33   ┆ 64.71   │
│ dcad7575db5a ┆ cessories    ┆ e01938cabda2 ┆              ┆   ┆       ┆         ┆      ┆         │
│ f1ba54…      ┆              ┆ a3e5cc…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ 350688d9dc1e ┆ bed_bath_tab ┆ f7ccf836d21b ┆ SP           ┆ … ┆ 6     ┆ 2       ┆ 23   ┆ 55.79   │
│ 75ff97be3263 ┆ le           ┆ 2fb1de375641 ┆              ┆   ┆       ┆         ┆      ┆         │
│ 63655e…      ┆              ┆ 05216c…      ┆              ┆   ┆       ┆         ┆      ┆         │
└──────────────┴──────────────┴──────────────┴──────────────┴───┴───────┴─────────┴──────┴─────────┘

In [4]:
mini.fx

shape: (10, 8)
┌─────────┬─────────┬──────┬────────┬─────────────┬─────────┬───────┬─────────┐
│ product ┆ country ┆ year ┆ volume ┆ price_in_lc ┆ fx_rate ┆ price ┆ revenue │
│ ---     ┆ ---     ┆ ---  ┆ ---    ┆ ---         ┆ ---     ┆ ---   ┆ ---     │
│ str     ┆ str     ┆ i64  ┆ i64    ┆ i64         ┆ f64     ┆ f64   ┆ f64     │
╞═════════╪═════════╪══════╪════════╪═════════════╪═════════╪═══════╪═════════╡
│ A       ┆ US      ┆ 2020 ┆ 100    ┆ 10          ┆ 1.0     ┆ 10.0  ┆ 1000.0  │
│ B       ┆ Japan   ┆ 2020 ┆ 200    ┆ 15          ┆ 1.2     ┆ 18.0  ┆ 3600.0  │
│ C       ┆ China   ┆ 2020 ┆ 400    ┆ 12          ┆ 1.5     ┆ 18.0  ┆ 7200.0  │
│ C       ┆ Japan   ┆ 2020 ┆ 200    ┆ 15          ┆ 1.2     ┆ 18.0  ┆ 3600.0  │
│ B       ┆ China   ┆ 2020 ┆ 400    ┆ 12          ┆ 1.5     ┆ 18.0  ┆ 7200.0  │
│ A       ┆ US      ┆ 2021 ┆ 150    ┆ 11          ┆ 1.0     ┆ 11.0  ┆ 1650.0  │
│ B       ┆ Japan   ┆ 2021 ┆ 150    ┆ 15          ┆ 1.15    ┆ 17.25 ┆ 2587.5  │
│ C       ┆ China   ┆ 2021 ┆ 420    ┆ 9           ┆ 1.7     ┆ 15.3  ┆ 6426.0  │
│ C       ┆ Japan   ┆ 2021 ┆ 150    ┆ 15          ┆ 1.15    ┆ 17.25 ┆ 2587.5  │
│ B       ┆ China   ┆ 2021 ┆ 420    ┆ 9           ┆ 1.7     ┆ 15.3  ┆ 6426.0  │
└─────────┴─────────┴──────┴────────┴─────────────┴─────────┴───────┴─────────┘

In [ ]:
import ibis
from ibis import deferred as c

ibis.options.interactive = True

In [ ]:
con = ibis.polars.connect(tables={"sales": mini.fx})
t = con.table("sales")
t

┏━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┓
┃ product ┃ country ┃ year  ┃ volume ┃ price_in_lc ┃ fx_rate ┃ price   ┃ revenue ┃
┡━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━┩
│ string  │ string  │ int64 │ int64  │ int64       │ float64 │ float64 │ float64 │
├─────────┼─────────┼───────┼────────┼─────────────┼─────────┼─────────┼─────────┤
│ A       │ US      │  2020 │    100 │          10 │    1.00 │   10.00 │  1000.0 │
│ B       │ Japan   │  2020 │    200 │          15 │    1.20 │   18.00 │  3600.0 │
│ C       │ China   │  2020 │    400 │          12 │    1.50 │   18.00 │  7200.0 │
│ C       │ Japan   │  2020 │    200 │          15 │    1.20 │   18.00 │  3600.0 │
│ B       │ China   │  2020 │    400 │          12 │    1.50 │   18.00 │  7200.0 │
│ A       │ US      │  2021 │    150 │          11 │    1.00 │   11.00 │  1650.0 │
│ B       │ Japan   │  2021 │    150 │          15 │    1.15 │   17.25 │  2587.5 │
│ C       │ China   │  2021 │    420 │           9 │    1.70 │   15.30 │  6426.0 │
│ C       │ Japan   │  2021 │    150 │          15 │    1.15 │   17.25 │  2587.5 │
│ B       │ China   │  2021 │    420 │           9 │    1.70 │   15.30 │  6426.0 │
└─────────┴─────────┴───────┴────────┴─────────────┴─────────┴─────────┴─────────┘

In [ ]:
import pvm
import pvm.fields
import pvm.formulas
import pvm.pvm

importlib.reload(pvm)
importlib.reload(pvm.pvm)
importlib.reload(pvm.fields)
importlib.reload(pvm.formulas)
pass
pvm.__version__

'0.0.3'

In [ ]:
price = pvm.fields.RateField(
    "price",
    definition=c.revenue.sum() / c.volume.sum(),
    components=[
        pvm.fields.RateField(
            "fx_rate", definition=c.revenue.sum() / (c.price_in_lc * c.volume).sum()
        ),
        pvm.fields.QuantityField(
            "local_price", definition=(c.price_in_lc * c.volume).sum() / c.volume.sum()
        ),
    ],
)
volume = pvm.fields.QuantityField("volume", definition=c.volume.sum())
revenue = pvm.fields.Field(
    "revenue",
    # definition=c.revenue.sum(),
    components=[price, volume],
)

period_expression = c.year.cast(str)
period_order = ("2020", "2021")
hierarchy = ["country", "product"]
hierarchy = []

In [ ]:
p = pvm.pvm.PVM()
p.set_data(t)
p.set_graph(revenue)
p.set_periods(period_expression, period_order)
p.set_hierarchy(hierarchy)
p.calculate_effects()

┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┓
┃ revenue_2020 ┃ price_2020 ┃ fx_rate_2020 ┃ local_price_2020 ┃ price_rec_2020 ┃ volume_2020 ┃ revenue_2021 ┃ price_2021 ┃ fx_rate_2021 ┃ local_price_2021 ┃ price_rec_2021 ┃ volume_2021 ┃ price_change_2020 ┃ volume_change_2020 ┃ volume_effect_2020 ┃ price_effect_2020 ┃ fx_rate_change_2020 ┃ local_price_change_2020 ┃ local_price_effect_2020 ┃ fx_rate_effect_2020 ┃ price_rec_effect_2020 ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━┩
│ float64      │ float64    │ float64      │ float64          │ float64        │ int64       │ float64      │ float64    │ float64      │ float64          │ float64        │ int64       │ float64           │ int64              │ float64            │ float64           │ float64             │ float64                 │ float64                 │ float64             │ float64               │
├──────────────┼────────────┼──────────────┼──────────────────┼────────────────┼─────────────┼──────────────┼────────────┼──────────────┼──────────────────┼────────────────┼─────────────┼───────────────────┼────────────────────┼────────────────────┼───────────────────┼─────────────────────┼─────────────────────────┼─────────────────────────┼─────────────────────┼───────────────────────┤
│      22600.0 │  17.384615 │     1.361446 │        12.769231 │  -3.552714e-15 │        1300 │      19677.0 │  15.253488 │      1.43523 │        10.627907 │   1.776357e-15 │        1290 │         -2.131127 │                -10 │        -152.534884 │      -2770.465116 │            0.073784 │               -2.141324 │            -3995.279121 │         1224.814004 │          6.927792e-12 │
└──────────────┴────────────┴──────────────┴──────────────────┴────────────────┴─────────────┴──────────────┴────────────┴──────────────┴──────────────────┴────────────────┴─────────────┴───────────────────┴────────────────────┴────────────────────┴───────────────────┴─────────────────────┴─────────────────────────┴─────────────────────────┴─────────────────────┴───────────────────────┘