In [1]:
import importlib

In [ ]:
from datasets import mini, olist

importlib.reload(mini)
pass

In [3]:
olist.sales_data

shape: (108_323, 15)
┌──────────────┬──────────────┬──────────────┬──────────────┬───┬───────┬─────────┬──────┬─────────┐
│ product_id   ┆ product_cate ┆ seller_id    ┆ seller_state ┆ … ┆ month ┆ quarter ┆ week ┆ revenue │
│ ---          ┆ gory_name_en ┆ ---          ┆ ---          ┆   ┆ ---   ┆ ---     ┆ ---  ┆ ---     │
│ str          ┆ glish        ┆ str          ┆ str          ┆   ┆ i8    ┆ i8      ┆ i8   ┆ f64     │
│              ┆ ---          ┆              ┆              ┆   ┆       ┆         ┆      ┆         │
│              ┆ str          ┆              ┆              ┆   ┆       ┆         ┆      ┆         │
╞══════════════╪══════════════╪══════════════╪══════════════╪═══╪═══════╪═════════╪══════╪═════════╡
│ 4244733e06e7 ┆ cool_stuff   ┆ 48436dade18a ┆ SP           ┆ … ┆ 9     ┆ 3       ┆ 37   ┆ 72.19   │
│ ecb4970a6e26 ┆              ┆ c8b2bce089ec ┆              ┆   ┆       ┆         ┆      ┆         │
│ 83c13e…      ┆              ┆ 2a0412…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ e5f2d52b8021 ┆ pet_shop     ┆ dd7ddc04e1b6 ┆ SP           ┆ … ┆ 4     ┆ 2       ┆ 17   ┆ 259.83  │
│ 89ee658865ca ┆              ┆ c2c614352b38 ┆              ┆   ┆       ┆         ┆      ┆         │
│ 93d83a…      ┆              ┆ 3efe2d…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ c777355d18b7 ┆ furniture_de ┆ 5b51032eddd2 ┆ MG           ┆ … ┆ 1     ┆ 1       ┆ 2    ┆ 216.87  │
│ 2b67abbeef9d ┆ cor          ┆ 42adc84c38ac ┆              ┆   ┆       ┆         ┆      ┆         │
│ f44fd0…      ┆              ┆ ab88f2…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ 7634da152a46 ┆ perfumery    ┆ 9d7a1d34a505 ┆ SP           ┆ … ┆ 8     ┆ 3       ┆ 32   ┆ 25.78   │
│ 10f1595efa32 ┆              ┆ 240900642527 ┆              ┆   ┆       ┆         ┆      ┆         │
│ f14722…      ┆              ┆ 5ba1c2…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ ac6c3623068f ┆ garden_tools ┆ df560393f3a5 ┆ PR           ┆ … ┆ 2     ┆ 1       ┆ 5    ┆ 218.04  │
│ 30de03045865 ┆              ┆ 1e74553ab940 ┆              ┆   ┆       ┆         ┆      ┆         │
│ e4e100…      ┆              ┆ 04ba5c…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ …            ┆ …            ┆ …            ┆ …            ┆ … ┆ …     ┆ …       ┆ …    ┆ …       │
│ 4aa6014eceb6 ┆ housewares   ┆ b8bc237ba378 ┆ SC           ┆ … ┆ 4     ┆ 2       ┆ 17   ┆ 343.4   │
│ 82077f9dc4bf ┆              ┆ 8b23da09c0f1 ┆              ┆   ┆       ┆         ┆      ┆         │
│ febc05…      ┆              ┆ f3a328…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ 32e07fd91582 ┆ computers_ac ┆ f3c38ab65283 ┆ SP           ┆ … ┆ 7     ┆ 3       ┆ 28   ┆ 386.53  │
│ 2b0765e448c4 ┆ cessories    ┆ 6d21de61fb83 ┆              ┆   ┆       ┆         ┆      ┆         │
│ dd74c8…      ┆              ┆ 14b691…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ 72a30483855e ┆ sports_leisu ┆ c3cfdc648177 ┆ PR           ┆ … ┆ 10    ┆ 4       ┆ 43   ┆ 116.85  │
│ 2eafc67aee5d ┆ re           ┆ fdbbbb35635a ┆              ┆   ┆       ┆         ┆      ┆         │
│ c25604…      ┆              ┆ 37472c…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ 9c422a519119 ┆ computers_ac ┆ 2b3e4a2a3ea8 ┆ SP           ┆ … ┆ 8     ┆ 3       ┆ 33   ┆ 64.71   │
│ dcad7575db5a ┆ cessories    ┆ e01938cabda2 ┆              ┆   ┆       ┆         ┆      ┆         │
│ f1ba54…      ┆              ┆ a3e5cc…      ┆              ┆   ┆       ┆         ┆      ┆         │
│ 350688d9dc1e ┆ bed_bath_tab ┆ f7ccf836d21b ┆ SP           ┆ … ┆ 6     ┆ 2       ┆ 23   ┆ 55.79   │
│ 75ff97be3263 ┆ le           ┆ 2fb1de375641 ┆              ┆   ┆       ┆         ┆      ┆         │
│ 63655e…      ┆              ┆ 05216c…      ┆              ┆   ┆       ┆         ┆      ┆         │
└──────────────┴──────────────┴──────────────┴──────────────┴───┴───────┴─────────┴──────┴─────────┘

In [4]:
mini.fx

shape: (10, 8)
┌─────────┬─────────┬──────┬────────┬─────────────┬─────────┬───────┬─────────┐
│ product ┆ country ┆ year ┆ volume ┆ price_in_lc ┆ fx_rate ┆ price ┆ revenue │
│ ---     ┆ ---     ┆ ---  ┆ ---    ┆ ---         ┆ ---     ┆ ---   ┆ ---     │
│ str     ┆ str     ┆ i64  ┆ i64    ┆ i64         ┆ f64     ┆ f64   ┆ f64     │
╞═════════╪═════════╪══════╪════════╪═════════════╪═════════╪═══════╪═════════╡
│ A       ┆ US      ┆ 2020 ┆ 100    ┆ 10          ┆ 1.0     ┆ 10.0  ┆ 1000.0  │
│ B       ┆ Japan   ┆ 2020 ┆ 200    ┆ 15          ┆ 1.2     ┆ 18.0  ┆ 3600.0  │
│ C       ┆ China   ┆ 2020 ┆ 400    ┆ 12          ┆ 1.5     ┆ 18.0  ┆ 7200.0  │
│ C       ┆ Japan   ┆ 2020 ┆ 200    ┆ 15          ┆ 1.2     ┆ 18.0  ┆ 3600.0  │
│ B       ┆ China   ┆ 2020 ┆ 400    ┆ 12          ┆ 1.5     ┆ 18.0  ┆ 7200.0  │
│ A       ┆ US      ┆ 2021 ┆ 150    ┆ 11          ┆ 1.0     ┆ 11.0  ┆ 1650.0  │
│ B       ┆ Japan   ┆ 2021 ┆ 150    ┆ 15          ┆ 1.15    ┆ 17.25 ┆ 2587.5  │
│ C       ┆ China   ┆ 2021 ┆ 420    ┆ 9           ┆ 1.7     ┆ 15.3  ┆ 6426.0  │
│ C       ┆ Japan   ┆ 2021 ┆ 150    ┆ 15          ┆ 1.15    ┆ 17.25 ┆ 2587.5  │
│ B       ┆ China   ┆ 2021 ┆ 420    ┆ 9           ┆ 1.7     ┆ 15.3  ┆ 6426.0  │
└─────────┴─────────┴──────┴────────┴─────────────┴─────────┴───────┴─────────┘

In [ ]:
import ibis
from ibis import deferred as c

ibis.options.interactive = True

In [ ]:
con = ibis.polars.connect(tables={"sales": mini.fx})
t = con.table("sales")
t

┏━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┓
┃ product ┃ country ┃ year  ┃ volume ┃ price_in_lc ┃ fx_rate ┃ price   ┃ revenue ┃
┡━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━┩
│ string  │ string  │ int64 │ int64  │ int64       │ float64 │ float64 │ float64 │
├─────────┼─────────┼───────┼────────┼─────────────┼─────────┼─────────┼─────────┤
│ A       │ US      │  2020 │    100 │          10 │    1.00 │   10.00 │  1000.0 │
│ B       │ Japan   │  2020 │    200 │          15 │    1.20 │   18.00 │  3600.0 │
│ C       │ China   │  2020 │    400 │          12 │    1.50 │   18.00 │  7200.0 │
│ C       │ Japan   │  2020 │    200 │          15 │    1.20 │   18.00 │  3600.0 │
│ B       │ China   │  2020 │    400 │          12 │    1.50 │   18.00 │  7200.0 │
│ A       │ US      │  2021 │    150 │          11 │    1.00 │   11.00 │  1650.0 │
│ B       │ Japan   │  2021 │    150 │          15 │    1.15 │   17.25 │  2587.5 │
│ C       │ China   │  2021 │    420 │           9 │    1.70 │   15.30 │  6426.0 │
│ C       │ Japan   │  2021 │    150 │          15 │    1.15 │   17.25 │  2587.5 │
│ B       │ China   │  2021 │    420 │           9 │    1.70 │   15.30 │  6426.0 │
└─────────┴─────────┴───────┴────────┴─────────────┴─────────┴─────────┴─────────┘

In [ ]:
import pvm
import pvm.fields
import pvm.formulas
import pvm.pvm

importlib.reload(pvm)
importlib.reload(pvm.pvm)
importlib.reload(pvm.fields)
importlib.reload(pvm.formulas)
pass
pvm.__version__

'0.0.3'

In [ ]:
price = pvm.fields.RateField(
    "price",
    definition=c.revenue.sum() / c.volume.sum(),
    components=[
        pvm.fields.RateField(
            "fx_rate",
            definition=c.revenue.sum() / (c.price_in_lc * c.volume).sum(),
        ),
        pvm.fields.QuantityField(
            "local_price",
            definition=(c.price_in_lc * c.volume).sum() / c.volume.sum(),
        ),
    ],
)
volume = pvm.fields.QuantityField("volume", definition=c.volume.sum())
revenue = pvm.fields.Field(
    "revenue",
    # definition=c.revenue.sum(),
    components=[price, volume],
)

period_expression = c.year.cast(str)
period_order = ("2020", "2021")
hierarchy = ["country", "product"]
hierarchy = []

In [ ]:
p = pvm.pvm.PVM()
p.set_data(t)
p.set_graph(revenue)
p.set_periods(period_expression, period_order)
p.set_hierarchy(hierarchy)
p.calculate_effects()

┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┓
┃ revenue_2020 ┃ price_2020 ┃ fx_rate_2020 ┃ local_price_2020 ┃ price_rec_2020 ┃ volume_2020 ┃ revenue_2021 ┃ price_2021 ┃ fx_rate_2021 ┃ local_price_2021 ┃ price_rec_2021 ┃ volume_2021 ┃ price_change_2020 ┃ volume_change_2020 ┃ volume_effect_2020 ┃ price_effect_2020 ┃ fx_rate_change_2020 ┃ local_price_change_2020 ┃ local_price_effect_2020 ┃ fx_rate_effect_2020 ┃ price_rec_effect_2020 ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━┩
│ float64      │ float64    │ float64      │ float64          │ float64        │ int64       │ float64      │ float64    │ float64      │ float64          │ float64        │ int64       │ float64           │ int64              │ float64            │ float64           │ float64             │ float64                 │ float64                 │ float64             │ float64               │
├──────────────┼────────────┼──────────────┼──────────────────┼────────────────┼─────────────┼──────────────┼────────────┼──────────────┼──────────────────┼────────────────┼─────────────┼───────────────────┼────────────────────┼────────────────────┼───────────────────┼─────────────────────┼─────────────────────────┼─────────────────────────┼─────────────────────┼───────────────────────┤
│      22600.0 │  17.384615 │     1.361446 │        12.769231 │  -3.552714e-15 │        1300 │      19677.0 │  15.253488 │      1.43523 │        10.627907 │   1.776357e-15 │        1290 │         -2.131127 │                -10 │        -152.534884 │      -2770.465116 │            0.073784 │               -2.141324 │            -3995.279121 │         1224.814004 │          6.927792e-12 │
└──────────────┴────────────┴──────────────┴──────────────────┴────────────────┴─────────────┴──────────────┴────────────┴──────────────┴──────────────────┴────────────────┴─────────────┴───────────────────┴────────────────────┴────────────────────┴───────────────────┴─────────────────────┴─────────────────────────┴─────────────────────────┴─────────────────────┴───────────────────────┘

In [ ]:
import numpy as np
import pandas as pd

# Parameters
num_rows = 1000
markets = ["US", "EU", "APAC", "LATAM"]
years = [2020, 2021, 2022, 2023]
skus = [f"SKU-{i}" for i in range(1, 51)]

# Generate random data
data = {
    "SKU": np.random.choice(skus, num_rows),
    "Market": np.random.choice(markets, num_rows),
    "Year": np.random.choice(years, num_rows),
    "Unit Price (local currency)": np.random.uniform(5, 100, num_rows),
    "FX rate": np.random.uniform(0.5, 1.5, num_rows),
    "Volume Sold": np.random.randint(10, 1000, num_rows),
    "Flat Fee": np.random.uniform(100, 1000, num_rows),
    "Unit Cost (local currency)": np.random.uniform(3, 70, num_rows),
    "Cost FX rate": np.random.uniform(0.5, 1.5, num_rows),
}

# Create DataFrame
df = pd.DataFrame(data)

df

,SKU,Market,Year,Unit Price (local currency),FX rate,Volume Sold,Flat Fee,Unit Cost (local currency),Cost FX rate
0,SKU-12,APAC,2020,65.506793,1.395784,169,139.402372,55.790291,0.510729
1,SKU-29,LATAM,2021,81.236023,0.967858,344,107.903445,38.755941,0.682592
2,SKU-47,US,2022,49.077890,1.194132,967,794.086060,53.208650,1.471357
3,SKU-12,US,2021,93.973003,0.531122,126,516.384746,36.830237,0.987196
4,SKU-26,US,2022,24.684357,0.946839,476,330.069205,25.175780,1.389177
...,...,...,...,...,...,...,...,...,...
995,SKU-7,EU,2023,79.441122,0.723195,424,521.604907,57.210316,1.235180
996,SKU-22,APAC,2020,64.856316,0.754778,742,550.081980,12.545009,1.229900
997,SKU-42,APAC,2020,71.477091,1.008424,576,102.959967,30.460500,1.279687
998,SKU-9,US,2021,59.892090,0.721334,808,373.740356,52.460168,0.650142
999,SKU-36,LATAM,2022,89.471057,0.766930,910,877.316756,53.118500,1.358291

In [71]:
import faker
import numpy as np
import polars as pl

fake = faker.Faker()
fake.seed_instance(42)
fake.country()
rng = np.random.default_rng(42)

num_countries = 4
num_products = 5
num_customers = 10
country_currencies = [(fake.country(), fake.currency_code()) for _ in range(num_countries)]
fx_rates = {currency: rng.uniform(0.5, 1.5) for _, currency in country_currencies}

skus = ["SKU" + str(i) for i in range(num_products)]
base_prices = {sku: rng.uniform(5, 100) for sku in skus}
base_margins = {sku: rng.uniform(0.6, 0.8) for sku in skus}

customers = [fake.company() for _ in range(num_customers)]
years = [2020, 2021, 2022, 2023]
country_currencies

[('Bouvet Island (Bouvetoya)', 'ARS'),
 ('Saint Vincent and the Grenadines', 'JOD'),
 ('Ecuador', 'HRK'),
 ('Burundi', 'CDF')]

In [ ]:
data = []

for year in years:
    fx_rates = {currency: rng.normal(rate, 0.05) for currency, rate in fx_rates.items()}
    for country, currency in country_currencies:
        for sku in skus:
            for customer in customers:
                record = {
                    "year": year,
                    "country": country,
                    "currency": currency,
                    "sku": sku,
                    "customer": customer,
                    "unit_price": rng.normal(base_prices[sku], 5),
                    "fx_rate": fx_rates[currency],
                    "volume": rng.gamma(25, 3),
                    "flat_fee": rng.uniform(-20, 20) if rng.binomial(n=1, p=0.2) else 0,
                }
                record["unit_cost"] = rng.normal(record["unit_price"] * base_margins[sku], 2)
                record["cost_fx_rate"] = record["fx_rate"] * rng.normal(1, 0.05)
                if rng.binomial(n=1, p=0.5):
                    data.append(record)

df = pl.DataFrame(data).with_columns(
    (pl.col("unit_price") * pl.col("fx_rate")).alias("price_in_lc"),
    (pl.col("unit_cost") * pl.col("cost_fx_rate")).alias("cost_in_lc"),
    (pl.col("unit_price") * pl.col("volume") + pl.col("flat_fee")).alias("revenue"),
    (pl.col("unit_cost") * pl.col("volume")).alias("cost"),
)

df.to_pandas().to_clipboard(index=False)
print(df.shape)

(405, 15)

In [ ]:
df.write_parquet("datasets/fake/sales.parquet")